apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: grpc-echo-server
  name: grpc-echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      run: grpc-echo-server
  template:
    metadata:
      labels:
        run: grpc-echo-server
    spec:
      containers:
      - name: grpc-echo-server
        image: dhirajnair/grpc-echo-server
        env:
        - name: ECHO_SERVICE_PORT
          value: "8080"
        - name: ECHO_SERVER_SLEEP
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: grpc-echo-server
  name: grpc-echo-server
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  selector:
    run: grpc-echo-server
  sessionAffinity: None
  type: ClusterIP